name: Dev CI/CD Workflow
on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  dev-build-test-deploy:
    name: Dev Build Test and Deploy
    uses: .github/workflows/reusable-ci.yml@main
    with:
      environment: "dev"
