name: Dev CI/CD Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main 
  workflow_dispatch:
  
jobs:
  dev-build-test-deploy:
    name: Dev Build Test and Deploy
    uses: ./.github/workflows/reusable-ci.yml
    with:
      environment: "dev"
    secrets: inherit
