name: Prod CI/CD Workflow
# on:
#   workflow_dispatch:
jobs:
  prod-build-test-deploy:
    name: Prod Build Test and Deploy
    uses: .github/workflows/reusable-ci.yml@main
    with:
      environment: "prod"
